### PR TITLE
Make generated stubs compatible with flake8-pyi>=23.5.0

### LINKED ISSUE #523: Compatibility with flake8-pyi>=23.5.0
Hi! I just released [flake8-pyi v23.5.0](https://github.com/PyCQA/flake8-pyi/releases/tag/23.5.0).

When flake8-pyi is installed, it does a little bit of monkeypatching of pyflakes in order to reduce pyflakes false positives on `.pyi` files. (Pyflakes is one of the builtin plugins that comes with flake8. I'm not proud of the fact we monkey-patch pyflakes, but nobody's been able to think of a better solution so far.) In the latest release, we've updated our monkeypatching of pyflakes, so that many places where pyflakes used to emit false positives on typeshed code, it no longer does. That means that if I have `flake8-pyi==23.5.0` installed, the following `# noqa` comments in typeshed's generated protobuf stubs are all flagged as unused by the `flake8-noqa` plugin (v1.3.1):

```
stubs\protobuf\google\protobuf\compiler\plugin_pb2.pyi:128:155: NQA102 "# noqa: F821" has no matching violations
stubs\protobuf\google\protobuf\descriptor_pb2.pyi:255:148: NQA102 "# noqa: F821" has no matching violations
stubs\protobuf\google\protobuf\descriptor_pb2.pyi:336:150: NQA102 "# noqa: F821" has no matching violations
stubs\protobuf\google\protobuf\descriptor_pb2.pyi:657:155: NQA102 "# noqa: F821" has no matching violations
stubs\protobuf\google\protobuf\descriptor_pb2.pyi:919:142: NQA102 "# noqa: F821" has no matching violations
stubs\protobuf\google\protobuf\descriptor_pb2.pyi:936:144: NQA102 "# noqa: F821" has no matching violations
stubs\protobuf\google\protobuf\descriptor_pb2.pyi:1170:165: NQA102 "# noqa: F821" has no matching violations
stubs\protobuf\google\protobuf\type_pb2.pyi:125:133: NQA102 "# noqa: F821" has no matching violations
stubs\protobuf\google\protobuf\type_pb2.pyi:212:147: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\compiler\xla\service\hlo_pb2.pyi:806:156: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\compiler\xla\service\hlo_pb2.pyi:1079:156: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\compiler\xla\xla_data_pb2.pyi:851:155: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\compiler\xla\xla_data_pb2.pyi:1310:160: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\compiler\xla\xla_data_pb2.pyi:1418:138: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\compiler\xla\xla_data_pb2.pyi:1576:153: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\framework\api_def_pb2.pyi:50:146: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\framework\dataset_options_pb2.pyi:135:162: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\framework\graph_transfer_info_pb2.pyi:196:159: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\config_pb2.pyi:348:146: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\config_pb2.pyi:375:164: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\config_pb2.pyi:686:182: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\config_pb2.pyi:1086:150: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\core_platform_payloads_pb2.pyi:32:158: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\data_service_pb2.pyi:59:165: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\data_service_pb2.pyi:163:161: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\rewriter_config_pb2.pyi:70:146: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\rewriter_config_pb2.pyi:118:152: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\rewriter_config_pb2.pyi:135:168: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\rewriter_config_pb2.pyi:154:154: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\saved_object_graph_pb2.pyi:475:152: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\saver_pb2.pyi:29:174: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\struct_pb2.pyi:334:159: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\tensor_bundle_pb2.pyi:44:157: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\tpu\compilation_result_pb2.pyi:36:160: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\tpu\optimization_parameters_pb2.pyi:738:158: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\tpu\optimization_parameters_pb2.pyi:805:159: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\tpu\optimization_parameters_pb2.pyi:846:161: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\tpu\topology_pb2.pyi:31:170: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\tpu\tpu_embedding_configuration_pb2.pyi:30:153: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\tpu\tpu_embedding_configuration_pb2.pyi:51:177: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\protobuf\verifier_config_pb2.pyi:29:146: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\util\event_pb2.pyi:151:140: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\util\event_pb2.pyi:202:156: NQA102 "# noqa: F821" has no matching violations
stubs\tensorflow\tensorflow\core\util\test_log_pb2.pyi:486:157: NQA102 "# noqa: F821" has no matching violations
```

Some of these stubs have been generated by typeshed's [`generate_proto_stubs.sh` script](https://github.com/python/typeshed/blob/main/scripts/generate_proto_stubs.sh), and some by our newer [`sync_tensorflow_protobuf_stubs.sh` script](https://github.com/python/typeshed/blob/main/scripts/sync_tensorflow_protobuf_stubs.sh). Both scripts use `mypy-protobuf` to generate the stubs.

Could we possibly update the logic by which mypy-protobuf automatically adds these `noqa` comments to the stubs it generates, so that the stubs it generates are compatible with `flake8-pyi==23.5.0`?

I'm not too familiar with mypy-protobuf, but it looks like the logic that needs updating might be here?

https://github.com/nipunn1313/mypy-protobuf/blob/ed77525352cefd90b03b8b8a69cc06d0e191d7be/mypy_protobuf/main.py#L353-L355

Thanks!

### PR DESCRIPTION
**Pull request by AlexWaygood**
Fixes #523.

It's my first time playing around with this code base, so it's possible I've screwed something up!

### CODE REVIEW

**Comment by AlexWaygood** [comment]
I believe this PR fixes the linting failures you're seeing on `main` and on all the open dependabot PRs (e.g. https://github.com/nipunn1313/mypy-protobuf/actions/runs/4924285741/jobs/8797147613?pr=527)

**Comment by nipunn1313** [comment]
this lgtm! I unfortunately lost track of this PR and ended up reimplementing the same stuff on main - but I appreciate the assist.

**Comment by nipunn1313** [comment]
I'll grab your Changelog entry and use it and add you to the contributors. Thx!

**Comment by AlexWaygood** [comment]
Thanks! Sorry just realised I forgot to respond here -- no worries about losing track of the PR :)

**Pull request closed without merging**
